config/routes.rb
Rails.application.routes.draw do
  resources :topics

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'ruby-items', to: 'portfolios#ruby_on_rails'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
      get :toggle_featured
    end
  end

  mount ActionCable.server => '/cable
  '
  root to: 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  enum featured: { standard: 0, featured: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body, :topic_id
  validates :body, length: { minimum: 250, maximum: 10000 }

  belongs_to :topic

  has_many :comments, dependent: :destroy

  def falsify_all_others
    Blog.where('id != ?', self.id).update_all("featured = 0")
  end

  def self.recent
    order("created_at DESC")
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status, :toggle_featured]
  before_action :set_topics, only: [:index, :show, :new, :edit, :create]
  before_action :monthly_blogs, only: [:index, :show, :new, :edit, :create]
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    @featured = Blog.find_by( featured: 1 )
    @page_title = "Steph Simpson | My Portfolio Blog"
    if logged_in?(:site_admin)
      if params[:topic]
        @topic = Topic.find_by(title: params[:topic])
        @blogs = Blog.recent.where( featured: 0 ).where(topic_id: @topic.id).page(params[:page]).per(3)
      else
        @blogs = Blog.recent.where( featured: 0 ).page(params[:page]).per(3)
      end
    else
      if params[:topic]
        @topic = Topic.find_by(title: params[:topic])
        @blogs = Blog.recent.where( featured: 0 ).where( status: 1 ).where(topic_id: @topic.id).page(params[:page]).per(3)
      elsif params[:month]
        date = Date.parse("1 #{params[:month]}")
        @blogs = Blog.recent.where( featured: 0 ).where( status: 1 ).where(:created_at => date..date.end_of_month).page(params[:page]).per(3)
      else
        @blogs = Blog.recent.where( featured: 0 ).where( status: 1 ).page(params[:page]).per(3)
      end
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    if logged_in?(:site_admin) || @blog.published?
      @blog = Blog.includes(:comments).friendly.find(params[:id])
      @comment = Comment.new
      @page_title = "Steph Simpson | #{@blog.title}"
      @seo_keywords = @blog.body
    else
      redirect_to blogs_path, notice: "You are not authorized to access that page"
    end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
    @page_title = "Steph Simpson | New Blog"
  end

  # GET /blogs/1/edit
  def edit
    @page_title = "Steph Simpson | Edit #{@blog.title}"
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    @blog.draft? ? @blog.published! : @blog.draft!
    redirect_to blogs_url, notice: 'Blog status has been updated!'
  end

  def toggle_featured
    if @blog.featured?
      @blog.standard!
    else
      @blog.featured!
      @blog.published!
      @blog.falsify_all_others
    end
    redirect_to blogs_url, notice: 'Featured blog set!'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    def set_topics
      @topic_nav = Topic.with_blogs.left_joins(:blogs).group(:id).order('COUNT(blogs.id) DESC').limit(7)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id, :status)
    end

    def monthly_blogs
      @blogs_by_month = Blog.all.group_by { |blog| blog.updated_at.strftime("%B %Y") }
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper

  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 60
  end

  def set_status blog
    if blog.published?
      link_to "Set to Draft", toggle_status_blog_path(blog)
    else
      link_to "Set to Published", toggle_status_blog_path(blog)
    end
  end

  def set_featured blog
    if blog.standard?
      link_to "Set as Featured Blog", toggle_featured_blog_path(blog)
    else
      link_to "Set to Standard Blog", toggle_featured_blog_path(blog)
    end
  end

  def topic_helper(topic_params, topic_nav)
    if topic_params == topic_nav.title
      "active-topic"
    end
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      las_html_blocks: true
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/views/blogs/_admin_actions.html.erb
<% if logged_in?(:site_admin) %>
  <p class="blog-post-meta breadcrumb"><%= set_status blog %> |
  <%= set_featured blog %> |
  <%= link_to 'Edit', edit_blog_path(blog) %> |
  <%= link_to 'Delete', blog, method: :delete, data: { confirm: 'Are you sure?' } %></p>
<% end%>

app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to blog.title, blog %></h2>
  <p class="blog-post-meta"><%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>

    <%= render 'blogs/admin_actions', blog: blog %>

  <p><%= blog.body %></p>
</div>

app/views/blogs/_featured.html.erb
<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
  <div class="col-md-8 px-0">
    <h1 class="display-4 font-italic"><%= @featured.title %></h1>
    <p class="lead my-3"><%= @featured.body.truncate(200) %></p>
    <p class="lead mb-0"><%= link_to "Continue reading...", @featured, class: "text-white font-weight-bold" %></p>
  </div>
</div>

app/views/blogs/_form.html.erb
<div class="card-block">
  <%= form_with(model: blog, local: true) do |form| %>
    <% if blog.errors.any? %>
      <% blog.errors.full_messages.each do |error| %>
        <%= alert_generator error %>
      <% end %>
    <% end %>

    <div class="form-group">
      <%= form.text_field :title, class: "form-control", placeholder: 'Title' %>
    </div>

    <div class="form-group">
      <%= form.text_area :body, class: "form-control", rows: "5", placeholder: 'Content' %>
    </div>

    <div class="form-group">
      <%= form.collection_select(:topic_id, Topic.all, :id, :title,
                                  {
                                    prompt: "Pick a topic",
                                    selected: blog.topic
                                  },
                                    class: 'form-control dropdown-toggle') %>
    </div>

    <div class="form-group">
      <%= form.radio_button :status, 'draft' %>
      <%= form.label :status, 'Draft' %>
    </div>

    <div class="form-group">
      <%= form.radio_button :status, 'published' %>
      <%= form.label :status, 'Published' %>
    </div>

    <div class="form-group">
      <%= form.submit "Submit", class: "btn btn-dark" %>
    </div>
  <% end %>
</div>

app/views/blogs/_topic_nav.html.erb
<div class="nav-scroller py-1 mb-2">
  <nav class="nav d-flex justify-content-between">
    <% @topic_nav.each do |t| %>
      <%= link_to t.title, blogs_path("topic" => t.title), class:"p-2 text-muted #{topic_helper(params[:topic], t) if params[:topic]}" %>
    <% end %>
    <%= link_to "View All", blogs_path, class:"p-2 text-muted" %>
  </nav>
</div>

app/views/blogs/edit.html.erb
<div class="row">
<div class="col-md-8 blog-main">
  <h1>Editing Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blog_path(@blog) %>
</div>
<%= render "shared/blogs_aside", blogs_by_month: @blogs_by_month %>
</div>

app/views/blogs/index.html.erb
    <main role="main" class="container">
      <div class="row">
        <%= render "blogs/featured", featured: @featured %>
        <div class="col-md-8 blog-main">
          <%= paginate @blogs %>
          <%= render @blogs %>
        </div>
        <%= render "shared/blogs_aside", blogs_by_month: @blogs_by_month %>
      </div>
          <%= paginate @blogs %>
    </main>
  </div>

<br>

app/views/blogs/new.html.erb
<div class="row">
  <div class="col-md-8 blog-main">
    <h1>New Blog</h1>

    <%= render 'form', blog: @blog %>

    <%= link_to 'Back', blogs_path %>
  </div>
  <%= render "shared/blogs_aside", blogs_by_month: @blogs_by_month %>
</div>

app/views/blogs/show.html.erb
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8 blog-main">
          <h1><%= @blog.title %></h1>
          <nav class="breadcrumb">
            <%= link_to "Home", root_path, class: 'breadcrumb-item'%>
            <%= link_to "Blogs", blogs_path, class: 'breadcrumb-item'%>
            <%= link_to @blog.topic.title, blogs_path("topic" => @blog.topic.title), class: 'breadcrumb-item'%>
            <span class="breadcrumb-item active"><%= @blog.title %></span>

            <span class="ml-auto breadcrumb-icon">
              <%= link_to fa_icon('pencil'), edit_blog_path(@blog) if logged_in?(:site_admin)%>
              <%= link_to fa_icon('trash'), @blog, method: :delete, data: { confirm: "Are you sure you want to delete this post?" } if logged_in?(:site_admin)%>
            </span>
          </nav>
          <h5><%= @blog.topic.title %></h5>
          <p><%= markdown @blog.body %>
          <hr>
          <%= render 'comments/form', comment: @comment %>

          <div id="comments" data-blog-id="<%= @blog.id %>">
            <%= render @blog.comments.order("created_at DESC") %>
          </div>

        </div>
        <%= render "shared/blogs_aside", blogs_by_month: @blogs_by_month %>
      </div>
    </main>
  </div>
<script>
$('document').ready(function () {
  const textField = document.querySelector('textarea#comment_content');
  let counter = textField.parentElement.getElementsByClassName('counter')[0].innerText;
  textField.addEventListener('keyup', function () {
    const count = this.value.length;
    newCounter = counter - count;
    this.parentElement.querySelector('.counter').innerText = newCounter;
    if (newCounter < 0) {
      this.parentElement.querySelector('.counter').style.color = 'red';
    } else if (newCounter > 0) {
      this.parentElement.querySelector('.counter').style.color = 'black';
    }
  });
});
</script>
<br>