config/routes.rb
Rails.application.routes.draw do
  resources :topics

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'ruby-items', to: 'portfolios#ruby_on_rails'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
      get :toggle_featured
    end
  end

  mount ActionCable.server => '/cable
  '
  root to: 'pages#home'
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title

  has_many :blogs

  def self.with_blogs
    includes(:blogs).where.not(blogs: { id: nil })
  end

  def self.recent
    order("created_at DESC")
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:edit, :update, :destroy]
  before_action :set_topics, only: [:index, :show, :new, :edit, :create]
  before_action :monthly_blogs, only: [:index, :new, :edit]
  layout 'blog'
  access all: [:index], user: [:index], site_admin: :all

  def index
    @topics = Topic.recent.all.page(params[:page]).per(8)
  end

  def new
    @topic = Topic.new
  end

  def edit
    if @topic.blogs.length > 0
      redirect_to topics_path, notice: 'Topic can\'t be changed if it has blogs.'
    end
  end

  def create
    @topic = Topic.new(topic_params)
    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path, notice: 'Topic was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topics_path, notice: 'Topic was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    if @topic.blogs.length > 0
      redirect_to topics_path, notice: 'Topic can\'t be deleted if it has blogs.'
    else
      @topic.destroy
      respond_to do |format|
        format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end


  private

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def set_topics
    @topic_nav = Topic.with_blogs.left_joins(:blogs).group(:id).order('COUNT(blogs.id) DESC').limit(7)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def topic_params
    params.require(:topic).permit(:title)
  end

  def monthly_blogs
    @blogs_by_month = Blog.all.group_by { |blog| blog.created_at.strftime("%B %Y") }
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<div class="card-block">
  <%= form_with(model: @topic, local: true) do |form| %>
    <% if @topic.errors.any? %>
      <% @topic.errors.full_messages.each do |error| %>
        <%= alert_generator error %>
      <% end %>
    <% end %>

    <div class="form-group">
      <%= form.text_field :title, class: "form-control", placeholder: 'Title' %>
    </div>


    <div class="form-group">
      <%= form.submit "Submit", class: "btn btn-dark" %>
    </div>
  <% end %>
</div>

app/views/topics/_topic.html.erb
<div class="topic-post">
  <h4 class="topic-post-title"><%= topic.title %></h4>
  <div class="topic-details">
    <% if logged_in?(:site_admin) %>
      <div class="topic-post-meta">
      <%= link_to 'Edit', edit_topic_path(topic) %> |
      <%= link_to 'Delete', topic, method: :delete, data: { confirm: 'Are you sure?' } %></div>
    <% end%>
    <div class="topic-post-subtitle"><%= topic.blogs.count %> blogs under this topic</div>
    <div class="topic-time">Created <%= distance_of_time_in_words(topic.created_at, Time.now) %> ago</div>
  </div>
</div>

app/views/topics/edit.html.erb
<div class="row">
<div class="col-md-8 topic-main">
  <h1>Editing Topic</h1>

  <%= render 'form', topic: @topic %>

  <%= link_to 'Back', topics_path %>
</div>
<%= render "shared/blogs_aside", blogs_by_month: @blogs_by_month %>
</div>

app/views/topics/index.html.erb
<div class="row">
  <h1>Topics</h1>
  <%= link_to 'New Topic', new_topic_path, class: "btn btn-sm btn-outline-secondary m-3" if logged_in?(:site_admin) %>
</div>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8 blog-main">
          <%= paginate @topics %>
          <%= render @topics %>
        </div>
        <%= render "shared/blogs_aside", blogs_by_month: @blogs_by_month %>
      </div>
      <%= paginate @topics %>
    </main>
  </div>

<br>

app/views/topics/new.html.erb
<div class="row">
  <div class="col-md-8 topic-main">
    <h1>New Topic</h1>

    <%= render 'form', topic: @topic %>

    <%= link_to 'Back', topics_path %>
  </div>
  <%= render "shared/blogs_aside", blogs_by_month: @blogs_by_month %>
</div>