config/routes.rb
Rails.application.routes.draw do
  resources :topics

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'ruby-items', to: 'portfolios#ruby_on_rails'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
      get :toggle_featured
    end
  end

  mount ActionCable.server => '/cable
  '
  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  include Placeholder
  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.ruby_on_rails
    self.joins(:technologies).where(:technologies => {:name => "Ruby on Rails"})
  end

  def self.by_position
    self.order("position ASC")
  end

  # scope :ruby_on_rails, -> { where(subtitle: "Ruby on Rails") }

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
  layout "portfolio"
  access all: [:show, :index, :ruby_on_rails], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
    head :ok
  end

  def ruby_on_rails
    @ruby_portfolio_items = Portfolio.ruby_on_rails
  end

  def new
    @portfolio_item = Portfolio.new
    @portfolio_item.technologies.build
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)
    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @portfolio_item.technologies.build
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolio_show_path(@portfolio_item), notice: 'Portoflio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
  end

  def destroy
    #Destroy the record
    @portfolio_item.destroy
    # Redirect
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio item was successfully removed.' }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      :main_image,
                                      :thumb_image,
                                      technologies_attributes: [:id, :name, :_destroy]
                                     )
  end

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper

end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: "form-control" %>
      </div>
    <div class="form-group">
      <label class="btn btn-info">
        Upload a main image file <%= f.file_field :main_image %>
      </label>
    </div>
    <div class="form-group">
      <label class="btn btn-info">
        Upload a thumb image file <%= f.file_field :thumb_image  %>
      </label>
    </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control", rows: 10 %>
      </div>
    </div>
  </div>
<hr>
  <div class="col-md-12">
    <div>
    <h2>Technologies Used:</h2>
      <%= f.fields_for :technologies do |technology_form| %>
        <%= render 'technology_fields', f: technology_form %>
      <% end %>
      <div>
        <%= link_to_add_association 'Add Technology', f, :technologies %>
      </div>
    </div>
  </div>

  <div class="row">
  <div class="form-group col-md-6">
      <%= f.submit "Save Portfolio Item", class: "btn btn-dark btn-block" %>
    </div>
    <div class="form-group col-md-6">
      <%= link_to "Back", :back, class: "btn btn-light btn-block" %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="portolfio-card col-md-4" data-id="<%= portfolio_item.id %>">
  <div class="card mb-4 box-shadow">
    <%= image_tag portfolio_item.thumb_image.to_s, width: '100%' unless portfolio_item.thumb_image.nil? %>
    <div class="card-body">
      <p class="card-text">
      <span class="portfolio-title"><%= portfolio_item.title %></span><br>
      <span class="portfolio-subtitle"><%= portfolio_item.subtitle %></span>
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Show", portfolio_show_path(portfolio_item) %></button>
          <% if logged_in?(:site_admin) %>
          <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit", edit_portfolio_path(portfolio_item) %></button>
          <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Delete", portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %></button>
          <% end %>
        </div>
        <small class="text-muted tech-count">Technologies count: <%= portfolio_item.technologies.count %></small>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name%>
  <%= f.text_field :name, class: "form-control"%>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit Portfolio</h1>

  <%= render "form", portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div>
      <%= source_helper("alert alert-primary") %>
    </div>
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
      <%= render partial: "portfolio_item", collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h1>New Portfolio</h1>

  <%= render "form", portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/ruby_on_rails.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
      <% if @ruby_portfolio_items.size > 0 %>
        <%= render partial: "portfolio_item", collection: @ruby_portfolio_items %>
      <% else %>
        <div>
          <h5>Uh-oh!</h5><br>
          <p>Looks like there isn't anything here! Please go back to my portfolio index to see the rest of my projects!</p>
          <%= link_to "Back to the portfolio!", portfolios_path, class: "btn btn-info my-2" %>

        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
    <%= image_tag @portfolio_item.main_image.to_s, width: '100%' unless @portfolio_item.main_image.nil? %>
    </div>
    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>
      <hr>
      <h4><em><%= @portfolio_item.subtitle %></em></h4>
      <p><%= @portfolio_item.body %></p>
      <hr>
      <% if @portfolio_item.technologies.size > 0 %>
      <h3>Technologies used:</h3>

      <% @portfolio_item.technologies.each do |t|%>
        <p><%= t.name %></p>
      <% end %>
      <% end %>
      <% if logged_in?(:site_admin) %>
        <div>
          <%= link_to "Edit", edit_portfolio_path(@portfolio_item), class: "btn btn-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>