config/routes.rb
Rails.application.routes.draw do
  resources :topics

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'ruby-items', to: 'portfolios#ruby_on_rails'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
      get :toggle_featured
    end
  end

  mount ActionCable.server => '/cable
  '
  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner app-footer">
    <p><%= set_copyright %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto application-nav">
  <div class="inner">
    <h3 class="masthead-brand">Steph Simpson</h3>
    <nav class="nav nav-masthead justify-content-center app-nav">
      <%= nav_helper "nav-link", "span" %>
      <%= login_helper "nav-link"%>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p><%= set_copyright %></p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_nav.html.erb
<header class="blog-header py-3">
  <div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-5 pt-1">
      <%= nav_helper "text-muted m-1 blog-nav", "span" %>
    </div>
    <div class="col-2 text-center">
      <a class="blog-header-logo text-dark" href="#">Blog</a>
    </div>
    <div class="col-5 d-flex justify-content-end align-items-center">
      <%= link_to 'Topics', topics_path, class: "btn btn-sm btn-outline-secondary m-2" if logged_in?(:site_admin) %>
      <%= link_to 'New Blog', new_blog_path, class: "btn btn-sm btn-outline-secondary m-2" if logged_in?(:site_admin) %>
      <%= login_helper "btn btn-sm btn-dark m-2" %>
    </div>
  </div>
</header>

app/views/shared/_blogs_aside.html.erb
<aside class="col-md-4 blog-sidebar">
  <div>
    <%= source_helper("alert alert-primary") %>
  </div>
  <div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">About My Blog</h4>
    <p class="mb-0">As a UBC Bachelor of Arts graduate turned Full Stack Web Developer, my education has taken a number of turns and I have questioned myself and my choices more times than I can count. This blog aims to help me explore new topics, deepen my understanding of topics I have previously touched on, and create and foster open discussion. If you would like to comment on a blog post, feel free to do so, or if you would like to get in touch I would love to hear from you! If you find yourself here, I hope you enjoy my ramblings, musings and, hopefully, my rare words of knowledge and wisdom.</p>
  </div>

  <div class="p-3">
    <h4 class="font-italic">Archives</h4>
    <ol class="list-unstyled mb-0">
      <% @blogs_by_month.each do |m,p| %>
        <li><%= link_to m, blogs_path(:month => m) %></li>
      <% end %>
    </ol>
  </div>

  <div class="p-3">
    <h4 class="font-italic">More Info</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/SjS16", target="_blank"><%= fa_icon "github" %></a></li>
      <li><a href="https://www.linkedin.com/in/sjs16", target="_blank"><%= fa_icon "linkedin" %></a></li>
    </ol>
  </div>
</aside>

app/views/shared/_nav.html.erb
    <div class="<%= location %>">
      <div><%= link_to "Home", root_path %></div>
      <div><%= link_to "About Me", about_path %></div>
      <div><%= link_to "Contact", contact_path %></div>
      <div><%= link_to "Blog", blogs_path %></div>
      <div><%= link_to "Portfolio", portfolios_path %></div>
    </div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <% if logged_in?(:site_admin) %>
      <%= link_to "Create New Item", new_portfolio_path  if logged_in?(:site_admin) %> |
      <% end %>
      <%= link_to "View all Portfolio Items", portfolios_path %> |
      <a href="#">Back to top</a>
    </p>
    <p><%= set_copyright %></p>
    <p>Want to know more? <%= link_to "Visit my homepage", root_path %> or check out <%= link_to "my blog", blogs_path %>!</p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">Check out some of my past projects and coding samples.</p>
    <p>
      <%= link_to "Find out more about me", about_path, class: "btn btn-info my-2" %>
      <%= link_to "Check out my blog", blogs_path, class: "btn btn-secondary my-2" %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-2">
          <%= image_tag 'Face.jpg', alt: "profile_image", class: "img-circular" %>
        </div>
        <div class="col-sm-7 py-4">
          <h3 class="text-white">About</h3>
          <p class="text-muted">Welcome to my portfolio! Here you will find examples of some of my past projects. Each item also contains a link to the github repo so you can check out my code, as well as a description of what the project was about, some of the technologies I used and anything else I feel is interesting about it!</p>
        </div>
        <div class="col-sm-1 offset-sm-2 py-4" style="text-align:right">
          <h3 class="text-white" style="margin-left: -38px;">Explore</h3>
          <ul class="list-unstyled" style="float: right">
            <%= nav_helper "text-white", "li" %>
            <li><%= login_helper "text-white"%></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="navbar navbar-dark bg-dark box-shadow">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <strong>Steph Simpson</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>